api_keys:
  anilist:
    client_id: optional_for_rate_limiting  # AniList 无需API密钥，可选配置
  bangumi:
    access_token: hKYw6NlNG7dupRnrE7CdgppUYoqv6VxupnHATCVJ  # 从 https://bgm.tv/dev/app 获取
  mal:
    auth_mode: client_id_only
    client_id: 4372369f4c49ab0f22e3405c1eb81032  # 从 https://myanimelist.net/apiconfig 获取
    client_secret: 203596caf450aee7f2bc35f3d4ad9ef204a6e92f3c11460194b2f002af05ab37  # 从 https://myanimelist.net/apiconfig 获取
logging:
  backup_count: 5
  file: data/logs/animescore.log
  level: INFO
  max_file_size: 10MB
model:
  bayesian:
    min_credible_votes: 1500
  platform_weights:
    anilist: 1.0
    bangumi: 1.0
    douban: 1.0
    filmarks: 0.9
    imdb: 0.6
    mal: 1.0
  site_statistics:
    method: seasonal
    min_seasonal_samples: 5
  weights:
    min_votes_threshold: 50
    min_websites: 1
    use_natural_log: true
# Data completion settings
data_completion:
  # Enable data completion (second-pass search for missing data)
  enabled: true

  # Maximum retry attempts per anime per website
  max_retry_per_anime: 3

  # Search timeout for each attempt (seconds)
  search_timeout: 30

  # Use alternative names for searching (English, simplified titles, etc.)
  use_alternative_names: true

  # Maximum parallel searches for completion
  parallel_searches: 5

  # Minimum existing websites required to attempt completion
  # (Skip completion for anime with very few existing ratings)
  min_existing_websites: 1

  # Priority websites for completion (attempt these first)
  priority_websites: ["bangumi", "mal", "anilist"]

  # Websites to exclude from data completion (but still enabled for seasonal analysis)
  excluded_websites: []

seasonal:
  current_season: null
  min_episodes: 1
  season_buffer_days: 30
storage:
  cache_dir: data/cache
  cache_expiration: 24
  export_formats:
  - json
  - csv
  - xlsx
  results_dir: data/results
  final_results_dir: data/results/final_results  # 手动处理后的最终结果目录
websites:
  anilist:
    api_base_url: https://graphql.anilist.co
    base_url: null
    enabled: true
    rate_limit: 3.0
    timeout: 30
  bangumi:
    api_base_url: https://api.bgm.tv
    base_url: null
    enabled: true
    rate_limit: 1.0
    timeout: 30
  douban:
    api_base_url: null
    base_url: https://movie.douban.com
    enabled: true    # 启用豆瓣（但在数据补全中排除）
    rate_limit: 3.0  # 与成功的独立测试保持一致
    timeout: 30      # 与成功的独立测试保持一致
  filmarks:
    api_base_url: null
    base_url: https://filmarks.com
    enabled: true
    rate_limit: 3.0
    timeout: 30
  imdb:
    api_base_url: null
    base_url: https://www.imdb.com
    enabled: true
    rate_limit: 3.0
    timeout: 30
  mal:
    api_base_url: https://api.myanimelist.net/v2
    base_url: null
    enabled: true
    rate_limit: 2.0
    timeout: 30
